[package]
name = "truck-js"
version = "0.1.0"
authors = ["Yoshinori Tanimura <tanimura@ricos.co.jp>"]
edition = "2021"
description = "Javascript wrapper for truck"
homepage = "https://github.com/ricosjp/truck"
repository = "https://github.com/ricosjp/truck"
license = "Apache-2.0"

keywords = ["truck", "graphics"]
categories = ["graphics"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
derive_more = "0.99.17"
rustc-hash = "1.1.0"
serde_json = "1.0.72"
truck-modeling = "0.3.0"
truck-meshalgo = "0.1.0"
truck-shapeops = "0.1.0"
wasm-bindgen = "0.2.78"
wee_alloc = { version = "0.4.5", optional = true }
